server.port=9090
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
spring.application.name=admin-server
spring.security.user.name=admin
spring.security.user.password=admin123
spring.boot.admin.ui.title=BusinessFlow Admin
spring.boot.admin.ui.brand=BusinessFlow Admin
