server.port=8080
spring.application.name=gateway-service
spring.main.web-application-type=reactive
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.initial-instance-info-replication-interval-seconds=5
eureka.client.registry-fetch-interval-seconds=5
eureka.client.instance-info-replication-interval-seconds=5
spring.boot.admin.client.url=http://admin-server:9090
spring.boot.admin.client.username=admin
spring.boot.admin.client.password=admin123
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://auth-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=billing-service
spring.cloud.gateway.routes[1].uri=http://billing-service:8084
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/invoices/**

spring.cloud.gateway.routes[2].id=receipt-service
spring.cloud.gateway.routes[2].uri=http://receipt-service:8087
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/receipts/**
