server.port=8084
spring.application.name=billing-service

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.initial-instance-info-replication-interval-seconds=5
eureka.client.registry-fetch-interval-seconds=5
eureka.client.instance-info-replication-interval-seconds=5

spring.boot.admin.client.url=http://admin-server:9090
spring.boot.admin.client.username=admin
spring.boot.admin.client.password=admin123

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true

# MySQL persistence
spring.datasource.url=${DB_URL:jdbc:mysql://mysql:3306/billing_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:businessflow}
spring.datasource.password=${DB_PASSWORD:businessflow}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Integracion con Customer Service
billing.customer-service-url=${CUSTOMER_SERVICE_URL:http://customer-service:8082}

# Redis Configuration
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

# RabbitMQ Configuration
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
